apiVersion: v1
kind: Service
metadata:
  name: apiconsumer-svc
  labels:
    app: apiconsumer-app
spec:
  ports:
    - port: 80
      targetPort: 9000
  selector:
    app: apiconsumer-app
  type: LoadBalancer
