apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-server
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /myVolume
    server: 10.71.0.58 #to be changed to actual server IP
